### ISSUE TITLE
Create page "Послуги"

### ISSUE THREAD

**Issue by GGO-web** [GGO-web/Unimay#60]
Should has the same blocks as in the main page

**Comment by alexey-sevastynov** [comment]
maybe you mean make it like the Team page? and just add the Services block there

**Comment by alexey-sevastynov** [comment]
> Should has the same blocks as in the main page

maybe you mean make it like the Team page? and just add the Services block there
![image](https://github.com/GGO-web/Unimay/assets/97807120/05c42d62-70b7-401b-8e3d-6d4535da02c1)

**Comment by GGO-web** [comment]
I think it should be a separate page, the "Team" page specifically about the team and their contacts

**Comment by GGO-web** [comment]
![image](https://github.com/GGO-web/Unimay/assets/68842054/dc5c2ec2-9000-4247-9328-c923ba806392)

this block should be duplicated in mentioned page
